// <auto-generated />
namespace Arthur.ORM.Infra.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class MF_ORM_Arthur : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MF_ORM_Arthur));
        
        string IMigrationMetadata.Id
        {
            get { return "201807171819264_MF_ORM_Arthur"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
