CREATE TABLE [dbo].[TBDESTINATARIO]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [Nome] VARCHAR(100) NOT NULL, 
    [Documento] VARCHAR(20) NOT NULL, 
    [TipoDeDocumento] VARCHAR(4) NOT NULL, 
    [InscricaoEstadual] VARCHAR(15) NULL, 
    [EnderecoId] INT NOT NULL, 
    CONSTRAINT [FK_TBDESTINATARIO_TBENDERECO] FOREIGN KEY ([EnderecoId]) REFERENCES [TBENDERECO]([Id])
)
