CREATE TABLE [dbo].[TBNOTAFISCAL]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [TransportadorId] INT NOT NULL, 
    [DestinatarioId] INT NOT NULL, 
    [EmitenteId] INT NOT NULL, 
    [NaturezaDaOperacao] VARCHAR(100) NOT NULL, 
    [DataEntrada] DATETIME NOT NULL, 
    CONSTRAINT [FK_TBNOTAFISCAL_TBTRANSPORTADOR] FOREIGN KEY ([TransportadorId]) REFERENCES [TBTRANSPORTADOR]([Id]), 
    CONSTRAINT [FK_TBNOTAFISCAL_TBDESTINATARIO] FOREIGN KEY ([DestinatarioId]) REFERENCES [TBDESTINATARIO]([Id]), 
    CONSTRAINT [FK_TBNOTAFISCAL_TBEMITENTE] FOREIGN KEY ([EmitenteId]) REFERENCES [TBEMITENTE]([Id])
)
