CREATE TABLE [dbo].[TBTRANSPORTADOR]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[Nome] VARCHAR(100) NOT NULL, 
    [Documento] VARCHAR(20) NOT NULL, 
    [TipoDocumento] VARCHAR(4) NOT NULL, 
    [InscricaoEstadual] VARCHAR(15) NOT NULL,
	[ResponsabilidadeFrete] BIT NOT NULL, 
    [EnderecoId] INT NOT NULL,
	CONSTRAINT [FK_TBTRABSPORTADOR_TBENDERECO] FOREIGN KEY ([EnderecoId]) REFERENCES [TBENDERECO]([Id])
)
