USE [master]
GO
/****** Object:  Database [LotericaDB]    Script Date: 23/05/2018 15:47:21 ******/
CREATE DATABASE [LotericaDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'LotericaDB', FILENAME = N'C:\Users\ndduser\LotericaDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'LotericaDB_log', FILENAME = N'C:\Users\ndduser\LotericaDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [LotericaDB] SET COMPATIBILITY_LEVEL = 130
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LotericaDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [LotericaDB] SET ANSI_NULL_DEFAULT ON 
GO
ALTER DATABASE [LotericaDB] SET ANSI_NULLS ON 
GO
ALTER DATABASE [LotericaDB] SET ANSI_PADDING ON 
GO
ALTER DATABASE [LotericaDB] SET ANSI_WARNINGS ON 
GO
ALTER DATABASE [LotericaDB] SET ARITHABORT ON 
GO
ALTER DATABASE [LotericaDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [LotericaDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [LotericaDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [LotericaDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [LotericaDB] SET CURSOR_DEFAULT  LOCAL 
GO
ALTER DATABASE [LotericaDB] SET CONCAT_NULL_YIELDS_NULL ON 
GO
ALTER DATABASE [LotericaDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [LotericaDB] SET QUOTED_IDENTIFIER ON 
GO
ALTER DATABASE [LotericaDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [LotericaDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [LotericaDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [LotericaDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [LotericaDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [LotericaDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [LotericaDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [LotericaDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [LotericaDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [LotericaDB] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [LotericaDB] SET  MULTI_USER 
GO
ALTER DATABASE [LotericaDB] SET PAGE_VERIFY NONE  
GO
ALTER DATABASE [LotericaDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [LotericaDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [LotericaDB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [LotericaDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [LotericaDB] SET QUERY_STORE = OFF
GO
USE [LotericaDB]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO
USE [LotericaDB]
GO
/****** Object:  Table [dbo].[Aposta]    Script Date: 23/05/2018 15:47:21 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Aposta](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Numeros] [varchar](50) NOT NULL,
	[Data] [datetime] NOT NULL,
	[IdConcurso] [int] NOT NULL,
	[Validade] [datetime] NOT NULL,
	[Valor] [float] NOT NULL,
	[IdBolao] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Bolao]    Script Date: 23/05/2018 15:47:22 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Bolao](
	[Id] [int] IDENTITY(1,1) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Concurso]    Script Date: 23/05/2018 15:47:22 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Concurso](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Data] [datetime] NOT NULL,
	[IsFechado] [bit] NOT NULL,
	[Premio] [real] NOT NULL,
	[IdResultado] [int] NULL,
	[PremioQuadra] [real] NOT NULL,
	[PremioQuina] [real] NOT NULL,
	[PremioSena] [real] NOT NULL,
	[GanhadoresQuadra] [int] NOT NULL,
	[GanhadoresQuina] [int] NOT NULL,
	[GanhadoresSena] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Faturamento]    Script Date: 23/05/2018 15:47:22 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Faturamento](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[IdConcurso] [int] NOT NULL,
	[ValorGanho] [real] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Resultado]    Script Date: 23/05/2018 15:47:22 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Resultado](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[NumerosSorteados] [varchar](50) NOT NULL,
	[MediaQuadra] [real] NOT NULL,
	[MediaQuina] [real] NOT NULL,
	[MediaSena] [real] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Aposta]  WITH CHECK ADD  CONSTRAINT [FK_Aposta_Bolao] FOREIGN KEY([IdBolao])
REFERENCES [dbo].[Bolao] ([Id])
GO
ALTER TABLE [dbo].[Aposta] CHECK CONSTRAINT [FK_Aposta_Bolao]
GO
ALTER TABLE [dbo].[Aposta]  WITH CHECK ADD  CONSTRAINT [FK_Aposta_Concurso] FOREIGN KEY([IdConcurso])
REFERENCES [dbo].[Concurso] ([Id])
GO
ALTER TABLE [dbo].[Aposta] CHECK CONSTRAINT [FK_Aposta_Concurso]
GO
ALTER TABLE [dbo].[Faturamento]  WITH CHECK ADD  CONSTRAINT [FK_Faturamento_Concurso] FOREIGN KEY([IdConcurso])
REFERENCES [dbo].[Concurso] ([Id])
GO
ALTER TABLE [dbo].[Faturamento] CHECK CONSTRAINT [FK_Faturamento_Concurso]
GO
USE [master]
GO
ALTER DATABASE [LotericaDB] SET  READ_WRITE 
GO
