// <auto-generated />
namespace Projeto_NFe.Infrastructure.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class NFe_v2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NFe_v2));
        
        string IMigrationMetadata.Id
        {
            get { return "201810111825452_NFe_v2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
